remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

include: 
  - _navigation.yml

# Enable header links
header_pages:
  - index.md
  - feedback.md
